### ISSUE TITLE
[Bug]: Package causes Laravel to completely stop working after installation

### ISSUE THREAD

**Issue by SwierczKacper** [chrisdicarlo/laravel-config-checker#2]
### What happened?

After installing the chrisdicarlo/laravel-config-checker package using composer require chrisdicarlo/laravel-config-checker, Laravel stops functioning entirely. An error occurs stating that "This package does not have a name," and suggests using $package->name("yourName"). The issue starts immediately after the installation, and it makes the entire Laravel application unusable. When i uninstall package, application starts working normally.

Screenshot: ![2024_09_27 12_05_07](https://github.com/user-attachments/assets/788545e5-98bd-4a5b-8dae-6bb5ba46e816)

composer.json content:

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.3",
        "ext-intl": "*",
        "ext-pdo": "*",
        "asana/asana": "^1.0",
        "axlon/laravel-postal-code-validation": "^3.6",
        "blade-ui-kit/blade-icons": "^1.5",
        "dipeshsukhia/laravel-html-minify": "^3.3",
        "doctrine/dbal": "^3.6",
        "endroid/qr-code": "^4.8",
        "fahlisaputra/laravel-minify": "^1.1",
        "google/apiclient": "^2.16",
        "guzzlehttp/guzzle": "^7.0.1",
        "ibericode/vat": "^2.0",
        "intervention/image": "^3.6",
        "jfcherng/php-diff": "^6.16",
        "laravel/fortify": "^1.17",
        "laravel/framework": "^10.0",
        "laravel/telescope": "^5.0",
        "laravel/tinker": "^2.5",
        "league/flysystem-aws-s3-v3": "^3.0",
        "livewire/livewire": "^2.12",
        "monarobase/country-list": "^3.4",
        "mpdf/mpdf": "^8.1",
        "php-webdriver/webdriver": "^1.15",
        "silber/page-cache": "^1.0",
        "slepic/apple-sign-in-client-secret-generator": "^0.1.2",
        "spatie/array-to-xml": "^3.2",
        "spatie/laravel-activitylog": "^4.8",
        "spatie/laravel-collection-macros": "^7.14",
        "spatie/laravel-data": "^4.6",
        "spatie/laravel-medialibrary": "^11.9",
        "spatie/laravel-responsecache": "^7.5",
        "spatie/pdf-to-image": "1.2",
        "symfony/dom-crawler": "^7.1",
        "symfony/http-client": "^6.1",
        "symfony/mailgun-mailer": "^6.1",
        "tinymce/tinymce": "^7.1"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.13",
        "barryvdh/laravel-ide-helper": "^3.1",
        "fakerphp/faker": "^1.9.1",
        "laravel/dusk": "*",
        "laravel/sail": "^1.16",
        "magentron/laravel-blade-lint": "^2.0",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "roave/security-advisories": "dev-latest",
        "spatie/laravel-ignition": "^2.0",
        "staudenmeir/dusk-updater": "*",
        "symplify/easy-coding-standard": "^12.2"
    },
    "autoload": {
        "files": [
            "app/helpers.php",
            "app/V1/Core/Domain/Helpers/helpers.php"
        ],
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "ecs-fix": [
            "vendor/bin/ecs check app/V1 --fix"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
`

### How to reproduce the bug

Install the package

### Package Version

^1.0

### PHP Version

8.3.4

### Laravel Version

^10.0

### Which operating systems does with happen with?

Linux

**Comment by chrisdicarlo** [comment]
I was able to reproduce it locally. I'm looking at the bug.

**Comment by chrisdicarlo** [comment]
I've fixed the bug - a new release should be out shortly.

**Comment by chrisdicarlo** [comment]
Fixed in #3
