### ISSUE TITLE
[Feature Request]: CLI flag for disabling progress

### ISSUE THREAD

**Issue by jacob418** [chrisdicarlo/laravel-config-checker#6]
### What happened?

*The 'feature request' form seems broken so i have to use this bug report form, sorry.*

When using the command in GitLab CI the progress bar produces a mess in the job log:

![image](https://github.com/user-attachments/assets/4a82cac6-b898-4794-9673-83e9797e6ad1)

It would be good if for CI this command had a cli flag, to turn off the output of the progress bar for example `--no-progress`.

### How to reproduce the bug

1. Push a laravel project to gitlab.com
2. Add a gitlab-ci job to run the `php artisan config:check` command in the ci script
3. Review the job-log

### Package Version

1.0.2

### PHP Version

8.3.0

### Laravel Version

10.43.0

### Which operating systems does with happen with?

Linux

**Comment by chrisdicarlo** [comment]
I'm adding this feature.  Thanks for the tip!

**Comment by chrisdicarlo** [comment]
This feature has been implemented but not yet tagged in a release.  @jacob418 Would you be able to test the flag in your build to ensure it cleans up the logs with your setup?
